language: python
python:
  - 3.6

install:
  #- echo "Aquí se instalan las dependencias"
  #- pip install django

before_script:
  - echo "Antes de ejecutar un script"
  - echo "Creación de entorno virtual"

script:
  
  - echo "Finalizar"


notifications:
email: false