language: python


matrix:
  include:
    - python: 3.6
      dist: xenial
      sudo: true

install:
  pip install -r requerimientos.txt

before_script:
  - echo "Antes de ejecutar un script"

script:
  - cd Accesos
  - python manage.py test
  - flake8 --exclude=*migrations*,*settings* .
  - coverage run --source='.' --omit=*test*,*migrations*,*__init*,*settings*,*apps*,*wsgi* manage.py test
  - coverage report
  - coverage html


notifications:
email: false